clinux/clinux/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("events/", include("events.urls")),
    path("members/", include("members.urls")),
    path("payments/", include("payments.urls")),
    path("", include("website.urls")),
]

clinux/events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("", views.EventListView.as_view(), name="event-list"),
    path("<int:pk>", views.EventDetailView.as_view(), name="event-detail"),
    path("sessions", views.EventSessionListView.as_view(), name="session-list"),
    path(
        "sessions/<int:pk>",
        views.EventSessionDetailView.as_view(),
        name="session-detail",
    ),
]

clinux/events/models.py
from django.db import models


class EventSession(models.Model):
    event = models.ForeignKey(
        "Event",
        on_delete=models.CASCADE,
        related_name="sessions",
        null=False,
        blank=False,
    )
    start = models.DateTimeField()
    end = models.DateTimeField()


class Event(models.Model):
    slug = models.SlugField(unique=True, max_length=100)
    title = models.CharField(null=False, blank=False, max_length=100)
    subtitle = models.CharField(default="", blank=True, max_length=100)
    description = models.TextField(default="", blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.title

clinux/events/views.py
from django.utils import timezone
from django.views.generic import DetailView
from django.views.generic.list import ListView

from . import models


class EventDetailView(DetailView):
    model = models.Event
    context_object_name = "event"


class EventSessionDetailView(DetailView):
    model = models.EventSession
    context_object_name = "session"


class EventListView(ListView):
    model = models.Event
    context_object_name = "events"
    paginate_by = 5  # if pagination is desired


class EventSessionListView(ListView):
    model = models.EventSession
    context_object_name = "sessions"
    paginate_by = 5  # if pagination is desired

clinux/events/templates/events/event_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ event.title }}</h1>

<p>{{ event.subtitle }}</p>
<p>{{ event.description }}</p>

Sessions:
<ul>
{% for session in event.sessions.all %}
  <li>
    <a href="{% url 'events:session-detail' pk=session.pk %}">
      {{ session.start }} --- {{ session.end }}
    </a>
  </li>
{% endfor %}
</ul>

{% endblock %}

clinux/events/templates/events/event_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Events</h1>
{% include 'events/partials/event_list.html' %}
{% endblock %}

clinux/events/templates/events/eventsession_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ session.event.title }}</h1>

<p>{{ session.event.subtitle }}</p>

<p>{{ session.event.description }}</p>

Appuntamento:
    {{ session.start }} - {{ session.end }}
{% endblock %}

clinux/events/templates/events/eventsession_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Events</h1>
<ul>
{% for session in sessions %}
    <li>{{ session.event.title }} @ {{ session.start|date }} </li>
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>
{% endblock %}